apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myopenshiftblog
    app.kubernetes.io/component: myopenshiftblog
    app.kubernetes.io/instance: myopenshiftblog
    app.kubernetes.io/name: myopenshiftblog
    app.kubernetes.io/part-of: myopenshiftblog
    app.openshift.io/runtime-namespace: myopenshiftblog
  name: myopenshiftblog
  namespace: myopenshiftblog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myopenshiftblog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: myopenshiftblog
        deploymentconfig: myopenshiftblog
    spec:
      containers:
      - env:
        - name: url
          value: https://myopenshiftblog.com
        - name: database__client
          value: mysql
        - name: database__connection__database
          value: myopenshiftblog
        - name: database__connection__host
          value: localhost
        - name: database__connection__password
          value: <redacted>
        - name: database__connection__user
          value: root
        - name: url
          value: https://myopenshiftblog.com
        image: docker.io/ghost:5.25
        imagePullPolicy: Always
        name: myopenshiftblog
        ports:
        - containerPort: 2368
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: myopenshiftblog-content
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: <redacted>
        image: mysql:8.0
        name: db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: myopenshiftblog-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: myopenshiftblog-content
        persistentVolumeClaim:
          claimName: myopenshiftblog-content
      - name: myopenshiftblog-db
        persistentVolumeClaim:
          claimName: myopenshiftblog-db
