apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mydatasciencebook
    app.kubernetes.io/component: mydatasciencebook
    app.kubernetes.io/instance: mydatasciencebook
    app.kubernetes.io/name: mydatasciencebook
    app.kubernetes.io/part-of: mydatasciencebook
    app.openshift.io/runtime-version: latest
  name: mydatasciencebook
  namespace: mydatasciencebook
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mydatasciencebook
    deploymentconfig: mydatasciencebook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
