kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myopenshiftblog
  namespace: myopenshiftblog
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: lso
  volumeMode: Filesystem
