kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mydatasciencebook-db
  namespace: mydatasciencebook
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
